</div>
<footer id="footer" class="footer">
    <div class="footer-container">
        <div class="container">
            <div class="row">
                <div class="col-xs-4">
                    <ul class="footer-links">
                        <li><a href="/" ><img class="" src="assets/img/logo_red_small.png" alt=""></a></li>
                    </ul>
                </div>
                <div class="col-xs-4">
                    <ul class="footer-icons">
                        <li><a href="home/"><img class="" src="assets/img/logo_horizontal.png" alt=""></a></li>
                        <!--                        <li><a href="https://www.youtube.com/channel/UClq6SD1HfMexPJeWs2lGKMQ" target="_blank"><img src="../../github/medialab/assets/images/yt.png" alt=""></a></li>-->
                        <!--                        <li><a href="/github/medialab/"><img src="/github/medialab/assets/img/logo_blue_small.png" alt=""></a></li>-->
                    </ul>
                </div>
                <div class="col-xs-4">
                    <ul class="footer-colofon">
                        <li>Copyright © 2017 - <a href="https://twitter.com/WotTheDeadZone" target="_blank">TheDeadZone</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<script src="https://use.fontawesome.com/2ff0e4635c.js"></script>
<script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="assets/js/script.js"></script>
</body>
</html>
